function(get_file_name_list LIB_DIRECTORY MASK WITH_ABS_PATH LIBRARY_NAME_LIST)
	file(GLOB LIB_FILES "${LIB_DIRECTORY}/${MASK}")
	set(RESULT_LIST)
	if(WITH_ABS_PATH)
		set(RESULT_LIST ${LIB_FILES})
	else()
		foreach(file ${LIB_FILES})
			get_filename_component(file_name ${file} NAME)
			list(APPEND RESULT_LIST ${file_name})
		endforeach()
	endif()
	set(${LIBRARY_NAME_LIST} ${RESULT_LIST} PARENT_SCOPE)
endfunction()
